### PR TITLE
Getting a rough calculation of WPM.

### PR DESCRIPTION
**Pull request by YingLiang2**
This is by no means done, but a rough calculation. 

I think we will need to do CPS to get a more accurate one. 

We will also need to deal with the re-rendering problem since our state variables for this calculation aren't updating instaneously.

### CODE REVIEW

**Comment by jonathanplacatka** [comment]
can't we just keep track of the # of words completed rather than keeping track of a list of completed words? (e.g just increment  a counter when onCompleteWord is called)

**Comment by YingLiang2** [comment]
We could, but whats the difference between keeping track of a list of completed strings vs a counter? @jonathanplacatka

**Comment by jonathanplacatka** [comment]
Because then you don't need a words list (which is a duplicate of something that exists in GameWindow), and you also don't need  a string parameter to onCompleteWord. If you're only using completedWords.length anyway, why keep track of all the text? just feels a lot cleaner to me. Its fine if you dont want to change though

**Review by jonathanplacatka — APPROVED** [review]

**Comment by YingLiang2** [comment]
I can change it, it's cleaner your way anyway.

**Comment by YingLiang2** [comment]
@jonathanplacatka Can you check this again to see if there is anymore changes you would like?

**Pull request merged**
